CREATE PROCEDURE [product].[product_detail_proc] 
@pipeline_name [VARCHAR](100),
@pipeline_run_id [VARCHAR](100),
@pipeline_trigger_name [VARCHAR](100),
@pipeline_trigger_id [VARCHAR](100),
@pipeline_trigger_type [VARCHAR](100),
@pipeline_trigger_date_time_utc [DATETIME2],
AS
BEGIN TRY
--LOAD-TYPE: Incremental temp2trans
WITH gen_hashkey as (
    SELECT
    [imprintable_flag] [varchar](1),
    [imprint_format_id] [varchar](3),
    [product_weight] decimal(38, 5),
    [ipp_product_flag] [varchar](1),
    [ipp_restricted_flag] [varchar](1),
    [ipp_subscription_flag] [varchar](1),
    [prepaid_maint_flag] [varchar](1),
    [prepaid_months] [decimal](38, 0),
    [prepaid_category_code] [varchar](1),
    [royalty_flag] [varchar](1),
    [billing_type_code] [varchar](5),
    [item_group_code] [varchar](5),
    [sub_item_group_code] [varchar](5),
    [manufacturer_part_number] [varchar](50),
    [ccats_number] [varchar](7),
    [es_business_unit_code] [varchar](5),
    [advocated_solution_code] [varchar](3),
    [service_tier_code] [varchar](2),
    [tm_remote_support] [varchar](1),
    [cross_selling_type_code] [varchar](10),
    [hw_sol_set_classification_code] [varchar](10),
    [support_class_code] [varchar](30),
    [item_type_code] [varchar](10),
    [item_model_code] [varchar](40),
    [returnable_flag] [varchar](1),
    [advanced_exchange_enabled_flag] [varchar](1),
    [os_type_code] [varchar](10),
    [min_storage] [decimal](38, 0),
    [min_storage_unit_code] [varchar](2),
    [max_storage] [decimal](38, 0),
    [max_storage_unit_code] [varchar](2),
    [storage_raid_code] [varchar](32),
    [erp_staging_bom_code] [varchar](20),
    [erp_business_unit_code] [varchar](20),
    [topline_reference_key] [varchar](40),
    [esdl_flag] [varchar](1),
    [marketed_product_line_code] [varchar](30),
    [license_category_code] [varchar](30),
    [license_feature_code] [varchar](30),
    [subscription_enabled_flag] [varchar](1),
    [product_detail_key] [decimal](38, 0),
    [annuity_flag] [varchar](1),
    [available_kit_version] [varchar](4),
    [bid_level_pricing_date] [varchar](35),
    [bid_level_pricing_flag] [varchar](1),
    [eccn_code] [varchar](8),
    [encryption_type_code] [varchar](2),
    [fcc_certification_code] [varchar](2),
    [fcc_id_number] [varchar](17),
    [fda_certification_code] [varchar](1),
    [gratis_demo_flag] [varchar](1),
    [gratis_internal_copy_flag] [varchar](1),
    [gratis_update_flag] [varchar](1),
    [hardware_language_code] [varchar](2),
    [hardware_power_code] [varchar](2),
    [harmonized_code] [varchar](15),
    [installable_type_code] [varchar](1),
    [installable_type_date] [varchar](35),
    [internal_use_flag] [varchar](1),
    [maint_price_exception_code] [varchar](12),
    [maint_price_exception_date] [varchar](35),
    [ncr_oem_ownership_code] [varchar](2),
    [ncrp_long_discontinued_flag] [varchar](1),
    [processor_quantity] [decimal](38, 0),
    [processor_type_key] [decimal](38, 0),
    [product_create_date] [varchar](35),
    [publication_language_code] [varchar](2),
    [serialized_product_flag] [varchar](1),
    [shipping_height] decimal(38, 5),
    [shipping_length] decimal(38, 5),
    [shipping_weight] decimal(38, 5),
    [shipping_width] decimal(38, 5),
    [software_language_code] [varchar](1),
    [software_license_code] [varchar](1),
    [sub_eccn_code] [varchar](9),
    [hazard_flag] [varchar](1),
    [software_license_type_code] [varchar](2),
    [installation_hours] [decimal](38, 0),
    [service_product_detail_key] [decimal](38, 0),
    [service_sponsor_org_key] [decimal](38, 0),
    [customs_description] [varchar](120),
    [service_invoice_flag] [varchar](1),
    [primary_uom_quantity] [decimal](38, 0),
    [wot_extract_flag] [varchar](1),
    [primary_uom_code] [varchar](3),
    [costing_uom_code] [varchar](1),
    [smd_product_code] [varchar](4),
    [sell_unit_upc] [varchar](12),
    [master_carton_upc] [varchar](14),
    [master_carton_quantity] [decimal](38, 0),
    [inner_carton_upc] [varchar](14),
    [inner_carton_quantity] [decimal](38, 0),
    [retail_catalog_flag] [varchar](1),
    [financial_catalog_flag] [varchar](1),
    [ncr_direct_flag] [varchar](1),
    [order_entry_message] [varchar](650),
    [product_comments] [varchar](650),
    FROM    [trans_product_gsdb_gsdb].[market_product_relationship_temp]
),
rn as (
    SELECT  *, ROW_NUMBER() OVER (PARTITION BY hash_key ORDER BY 
                 last_update_timestamp DESC,
				  infa_operation_time DESC,
                infa_sortable_sequence  DESC
        ) as _ELT_ROWNUMBERED
    FROM    gen_hashkey
),
data as (
    SELECT  *
    FROM    rn
    WHERE _ELT_ROWNUMBERED = 1
)
MERGE INTO    [trans_product_gsdb_gsdb].[market_product_relationship] tgt
USING (
    SELECT  *
    FROM    data
) src
ON ( src.[hash_key] = tgt.[hash_key] )
WHEN MATCHED THEN 
UPDATE SET
    [tgt].[imprintable_flag] = [src].[imprintable_flag],
    [tgt].[imprint_format_id] = [src].[imprint_format_id],
    [tgt].[product_weight] = [src].[product_weight],
    [tgt].[ipp_product_flag] = [src].[ipp_product_flag],
    [tgt].[ipp_restricted_flag] = [src].[ipp_restricted_flag],
    [tgt].[ipp_subscription_flag] = [src].[ipp_subscription_flag],
    [tgt].[prepaid_maint_flag] = [src].[prepaid_maint_flag],
    [tgt].[prepaid_months] = [src].[prepaid_months],
    [tgt].[prepaid_category_code] = [src].[prepaid_category_code],
    [tgt].[royalty_flag] = [src].[royalty_flag],
    [tgt].[billing_type_code] = [src].[billing_type_code],
    [tgt].[item_group_code] = [src].[item_group_code],
    [tgt].[sub_item_group_code] = [src].[sub_item_group_code],
    [tgt].[manufacturer_part_number] = [src].[manufacturer_part_number],
    [tgt].[ccats_number] = [src].[ccats_number],
    [tgt].[es_business_unit_code] = [src].[es_business_unit_code],
    [tgt].[advocated_solution_code] = [src].[advocated_solution_code],
    [tgt].[service_tier_code] = [src].[service_tier_code],
    [tgt].[tm_remote_support] = [src].[tm_remote_support],
    [tgt].[cross_selling_type_code] = [src].[cross_selling_type_code],
    [tgt].[hw_sol_set_classification_code] = [src].[hw_sol_set_classification_code],
    [tgt].[support_class_code] = [src].[support_class_code],
    [tgt].[item_type_code] = [src].[item_type_code],
    [tgt].[item_model_code] = [src].[item_model_code],
    [tgt].[returnable_flag] = [src].[returnable_flag],
    [tgt].[advanced_exchange_enabled_flag] = [src].[advanced_exchange_enabled_flag],
    [tgt].[os_type_code] = [src].[os_type_code],
    [tgt].[min_storage] = [src].[min_storage],
    [tgt].[min_storage_unit_code] = [src].[min_storage_unit_code],
    [tgt].[max_storage] = [src].[max_storage],
    [tgt].[max_storage_unit_code] = [src].[max_storage_unit_code],
    [tgt].[storage_raid_code] = [src].[storage_raid_code],
    [tgt].[erp_staging_bom_code] = [src].[erp_staging_bom_code],
    [tgt].[erp_business_unit_code] = [src].[erp_business_unit_code],
    [tgt].[topline_reference_key] = [src].[topline_reference_key],
    [tgt].[esdl_flag] = [src].[esdl_flag],
    [tgt].[marketed_product_line_code] = [src].[marketed_product_line_code],
    [tgt].[license_category_code] = [src].[license_category_code],
    [tgt].[license_feature_code] = [src].[license_feature_code],
    [tgt].[subscription_enabled_flag] = [src].[subscription_enabled_flag],
    [tgt].[product_detail_key] = [src].[product_detail_key],
    [tgt].[annuity_flag] = [src].[annuity_flag],
    [tgt].[available_kit_version] = [src].[available_kit_version],
    [tgt].[bid_level_pricing_date] = [src].[bid_level_pricing_date],
    [tgt].[bid_level_pricing_flag] = [src].[bid_level_pricing_flag],
    [tgt].[eccn_code] = [src].[eccn_code],
    [tgt].[encryption_type_code] = [src].[encryption_type_code],
    [tgt].[fcc_certification_code] = [src].[fcc_certification_code],
    [tgt].[fcc_id_number] = [src].[fcc_id_number],
    [tgt].[fda_certification_code] = [src].[fda_certification_code],
    [tgt].[gratis_demo_flag] = [src].[gratis_demo_flag],
    [tgt].[gratis_internal_copy_flag] = [src].[gratis_internal_copy_flag],
    [tgt].[gratis_update_flag] = [src].[gratis_update_flag],
    [tgt].[hardware_language_code] = [src].[hardware_language_code],
    [tgt].[hardware_power_code] = [src].[hardware_power_code],
    [tgt].[harmonized_code] = [src].[harmonized_code],
    [tgt].[installable_type_code] = [src].[installable_type_code],
    [tgt].[installable_type_date] = [src].[installable_type_date],
    [tgt].[internal_use_flag] = [src].[internal_use_flag],
    [tgt].[maint_price_exception_code] = [src].[maint_price_exception_code],
    [tgt].[maint_price_exception_date] = [src].[maint_price_exception_date],
    [tgt].[ncr_oem_ownership_code] = [src].[ncr_oem_ownership_code],
    [tgt].[ncrp_long_discontinued_flag] = [src].[ncrp_long_discontinued_flag],
    [tgt].[processor_quantity] = [src].[processor_quantity],
    [tgt].[processor_type_key] = [src].[processor_type_key],
    [tgt].[product_create_date] = [src].[product_create_date],
    [tgt].[publication_language_code] = [src].[publication_language_code],
    [tgt].[serialized_product_flag] = [src].[serialized_product_flag],
    [tgt].[shipping_height] = [src].[shipping_height],
    [tgt].[shipping_length] = [src].[shipping_length],
    [tgt].[shipping_weight] = [src].[shipping_weight],
    [tgt].[shipping_width] = [src].[shipping_width],
    [tgt].[software_language_code] = [src].[software_language_code],
    [tgt].[software_license_code] = [src].[software_license_code],
    [tgt].[sub_eccn_code] = [src].[sub_eccn_code],
    [tgt].[hazard_flag] = [src].[hazard_flag],
    [tgt].[software_license_type_code] = [src].[software_license_type_code],
    [tgt].[installation_hours] = [src].[installation_hours],
    [tgt].[service_product_detail_key] = [src].[service_product_detail_key],
    [tgt].[service_sponsor_org_key] = [src].[service_sponsor_org_key],
    [tgt].[customs_description] = [src].[customs_description],
    [tgt].[service_invoice_flag] = [src].[service_invoice_flag],
    [tgt].[primary_uom_quantity] = [src].[primary_uom_quantity],
    [tgt].[wot_extract_flag] = [src].[wot_extract_flag],
    [tgt].[primary_uom_code] = [src].[primary_uom_code],
    [tgt].[costing_uom_code] = [src].[costing_uom_code],
    [tgt].[smd_product_code] = [src].[smd_product_code],
    [tgt].[sell_unit_upc] = [src].[sell_unit_upc],
    [tgt].[master_carton_upc] = [src].[master_carton_upc],
    [tgt].[master_carton_quantity] = [src].[master_carton_quantity],
    [tgt].[inner_carton_upc] = [src].[inner_carton_upc],
    [tgt].[inner_carton_quantity] = [src].[inner_carton_quantity],
    [tgt].[retail_catalog_flag] = [src].[retail_catalog_flag],
    [tgt].[financial_catalog_flag] = [src].[financial_catalog_flag],
    [tgt].[ncr_direct_flag] = [src].[ncr_direct_flag],
    [tgt].[order_entry_message] = [src].[order_entry_message],
    [tgt].[product_comments] = [src].[product_comments],
        [tgt].[ingest_partition] = [src].[ingest_partition],
        [tgt].[ingest_channel] = [src].[ingest_channel],
        [tgt].[file_path] = [src].[file_path],
        [tgt].[root_path] = [src].[root_path],
        [tgt].[trans_load_date_time_utc] = GETDATE(),
        [tgt].[adle_transaction_code] = [src].[infa_operation_type],
		[tgt].[infa_operation_time]=[src].[infa_operation_time],
	    [tgt].[infa_sortable_sequence]=[src].[infa_sortable_sequence],
        [tgt].[pipeline_name] = @pipeline_name,
        [tgt].[pipeline_run_id] = @pipeline_run_id,
        [tgt].[pipeline_trigger_name] = @pipeline_trigger_name,
        [tgt].[pipeline_trigger_id] = @pipeline_trigger_id,
        [tgt].[pipeline_trigger_type] = @pipeline_trigger_type,
        [tgt].[pipeline_trigger_date_time_utc] = @pipeline_trigger_date_time_utc
WHEN NOT MATCHED THEN 
    INSERT (
    [imprintable_flag],
    [imprint_format_id],
    [product_weight],
    [ipp_product_flag],
    [ipp_restricted_flag],
    [ipp_subscription_flag],
    [prepaid_maint_flag],
    [prepaid_months],
    [prepaid_category_code],
    [royalty_flag],
    [billing_type_code],
    [item_group_code],
    [sub_item_group_code],
    [manufacturer_part_number],
    [ccats_number],
    [es_business_unit_code],
    [advocated_solution_code],
    [service_tier_code],
    [tm_remote_support],
    [cross_selling_type_code],
    [hw_sol_set_classification_code],
    [support_class_code],
    [item_type_code],
    [item_model_code],
    [returnable_flag],
    [advanced_exchange_enabled_flag],
    [os_type_code],
    [min_storage],
    [min_storage_unit_code],
    [max_storage],
    [max_storage_unit_code],
    [storage_raid_code],
    [erp_staging_bom_code],
    [erp_business_unit_code],
    [topline_reference_key],
    [esdl_flag],
    [marketed_product_line_code],
    [license_category_code],
    [license_feature_code],
    [subscription_enabled_flag],
    [product_detail_key],
    [annuity_flag],
    [available_kit_version],
    [bid_level_pricing_date],
    [bid_level_pricing_flag],
    [eccn_code],
    [encryption_type_code],
    [fcc_certification_code],
    [fcc_id_number],
    [fda_certification_code],
    [gratis_demo_flag],
    [gratis_internal_copy_flag],
    [gratis_update_flag],
    [hardware_language_code],
    [hardware_power_code],
    [harmonized_code],
    [installable_type_code],
    [installable_type_date],
    [internal_use_flag],
    [maint_price_exception_code],
    [maint_price_exception_date],
    [ncr_oem_ownership_code],
    [ncrp_long_discontinued_flag],
    [processor_quantity],
    [processor_type_key],
    [product_create_date],
    [publication_language_code],
    [serialized_product_flag],
    [shipping_height],
    [shipping_length],
    [shipping_weight],
    [shipping_width],
    [software_language_code],
    [software_license_code],
    [sub_eccn_code],
    [hazard_flag],
    [software_license_type_code],
    [installation_hours],
    [service_product_detail_key],
    [service_sponsor_org_key],
    [customs_description],
    [service_invoice_flag],
    [primary_uom_quantity],
    [wot_extract_flag],
    [primary_uom_code],
    [costing_uom_code],
    [smd_product_code],
    [sell_unit_upc],
    [master_carton_upc],
    [master_carton_quantity],
    [inner_carton_upc],
    [inner_carton_quantity],
    [retail_catalog_flag],
    [financial_catalog_flag],
    [ncr_direct_flag],
    [order_entry_message],
    [product_comments],
)VALUES(
    [src].[imprintable_flag],
    [src].[imprint_format_id],
    [src].[product_weight],
    [src].[ipp_product_flag],
    [src].[ipp_restricted_flag],
    [src].[ipp_subscription_flag],
    [src].[prepaid_maint_flag],
    [src].[prepaid_months],
    [src].[prepaid_category_code],
    [src].[royalty_flag],
    [src].[billing_type_code],
    [src].[item_group_code],
    [src].[sub_item_group_code],
    [src].[manufacturer_part_number],
    [src].[ccats_number],
    [src].[es_business_unit_code],
    [src].[advocated_solution_code],
    [src].[service_tier_code],
    [src].[tm_remote_support],
    [src].[cross_selling_type_code],
    [src].[hw_sol_set_classification_code],
    [src].[support_class_code],
    [src].[item_type_code],
    [src].[item_model_code],
    [src].[returnable_flag],
    [src].[advanced_exchange_enabled_flag],
    [src].[os_type_code],
    [src].[min_storage],
    [src].[min_storage_unit_code],
    [src].[max_storage],
    [src].[max_storage_unit_code],
    [src].[storage_raid_code],
    [src].[erp_staging_bom_code],
    [src].[erp_business_unit_code],
    [src].[topline_reference_key],
    [src].[esdl_flag],
    [src].[marketed_product_line_code],
    [src].[license_category_code],
    [src].[license_feature_code],
    [src].[subscription_enabled_flag],
    [src].[product_detail_key],
    [src].[annuity_flag],
    [src].[available_kit_version],
    [src].[bid_level_pricing_date],
    [src].[bid_level_pricing_flag],
    [src].[eccn_code],
    [src].[encryption_type_code],
    [src].[fcc_certification_code],
    [src].[fcc_id_number],
    [src].[fda_certification_code],
    [src].[gratis_demo_flag],
    [src].[gratis_internal_copy_flag],
    [src].[gratis_update_flag],
    [src].[hardware_language_code],
    [src].[hardware_power_code],
    [src].[harmonized_code],
    [src].[installable_type_code],
    [src].[installable_type_date],
    [src].[internal_use_flag],
    [src].[maint_price_exception_code],
    [src].[maint_price_exception_date],
    [src].[ncr_oem_ownership_code],
    [src].[ncrp_long_discontinued_flag],
    [src].[processor_quantity],
    [src].[processor_type_key],
    [src].[product_create_date],
    [src].[publication_language_code],
    [src].[serialized_product_flag],
    [src].[shipping_height],
    [src].[shipping_length],
    [src].[shipping_weight],
    [src].[shipping_width],
    [src].[software_language_code],
    [src].[software_license_code],
    [src].[sub_eccn_code],
    [src].[hazard_flag],
    [src].[software_license_type_code],
    [src].[installation_hours],
    [src].[service_product_detail_key],
    [src].[service_sponsor_org_key],
    [src].[customs_description],
    [src].[service_invoice_flag],
    [src].[primary_uom_quantity],
    [src].[wot_extract_flag],
    [src].[primary_uom_code],
    [src].[costing_uom_code],
    [src].[smd_product_code],
    [src].[sell_unit_upc],
    [src].[master_carton_upc],
    [src].[master_carton_quantity],
    [src].[inner_carton_upc],
    [src].[inner_carton_quantity],
    [src].[retail_catalog_flag],
    [src].[financial_catalog_flag],
    [src].[ncr_direct_flag],
    [src].[order_entry_message],
    [src].[product_comments],
        [src].[hash_key]
    );
END TRY
BEGIN CATCH
    DECLARE @db_name VARCHAR(200),
        @schema_name VARCHAR(200),
        @error_nbr INT,
        @error_severity INT,
        @error_state INT,
        @stored_proc_name VARCHAR(200),
        @error_message VARCHAR(8000),
        @created_date_time DATETIME2

    SET @db_name=DB_NAME()
    SET @schema_name=SUBSTRING (@pipeline_name, CHARINDEX('2', @pipeline_name) + 1, LEN(@pipeline_name) - CHARINDEX('2', @pipeline_name) - 3 )
    SET @error_nbr=ERROR_NUMBER()
    SET @error_severity=ERROR_SEVERITY()
    SET @error_state=ERROR_STATE()
    SET @stored_proc_name=ERROR_PROCEDURE()
    SET @error_message=ERROR_MESSAGE()
    SET @created_date_time=GETDATE()

    EXECUTE [adle_platform_orchestration].[elt_error_log_proc]
        @db_name,
        'ERROR',
        @schema_name,
        @error_nbr,
        @error_severity,
        @error_state,
        @stored_proc_name,
        'PROC',
        @error_message,
        @created_date_time,
        @pipeline_name,
        @pipeline_run_id,
        @pipeline_trigger_name,
        @pipeline_trigger_id,
        @pipeline_trigger_type,
        @pipeline_trigger_date_time_utc
        ;
    THROW;
END CATCH
;
GO
