CREATE PROCEDURE [product].[product_detail_proc] 
@pipeline_name [VARCHAR](100),
@pipeline_run_id [VARCHAR](100),
@pipeline_trigger_name [VARCHAR](100),
@pipeline_trigger_id [VARCHAR](100),
@pipeline_trigger_type [VARCHAR](100),
@pipeline_trigger_date_time_utc [DATETIME2],
AS
BEGIN TRY
--LOAD-TYPE: Incremental temp2trans
WITH gen_hashkey as (
    SELECT
      CAST([imprintable_flag] AS [varchar](1)) AS [imprintable_flag],
      CAST([imprint_format_id] AS [varchar](3)) AS [imprint_format_id],
      CAST([product_weight] AS [decimal](38, 5)) AS [product_weight],
      CAST([ipp_product_flag] AS [varchar](1)) AS [ipp_product_flag],
      CAST([ipp_restricted_flag] AS [varchar](1)) AS [ipp_restricted_flag],
      CAST([ipp_subscription_flag] AS [varchar](1)) AS [ipp_subscription_flag],
      CAST([prepaid_maint_flag] AS [varchar](1)) AS [prepaid_maint_flag],
      CAST([prepaid_months] AS [decimal](38, 0)) AS [prepaid_months],
      CAST([prepaid_category_code] AS [varchar](1)) AS [prepaid_category_code],
      CAST([royalty_flag] AS [varchar](1)) AS [royalty_flag],
      CAST([billing_type_code] AS [varchar](5)) AS [billing_type_code],
      CAST([item_group_code] AS [varchar](5)) AS [item_group_code],
      CAST([sub_item_group_code] AS [varchar](5)) AS [sub_item_group_code],
      CAST([manufacturer_part_number] AS [varchar](50)) AS [manufacturer_part_number],
      CAST([ccats_number] AS [varchar](7)) AS [ccats_number],
      CAST([es_business_unit_code] AS [varchar](5)) AS [es_business_unit_code],
      CAST([advocated_solution_code] AS [varchar](3)) AS [advocated_solution_code],
      CAST([service_tier_code] AS [varchar](2)) AS [service_tier_code],
      CAST([tm_remote_support] AS [varchar](1)) AS [tm_remote_support],
      CAST([cross_selling_type_code] AS [varchar](10)) AS [cross_selling_type_code],
      CAST([hw_sol_set_classification_code] AS [varchar](10)) AS [hw_sol_set_classification_code],
      CAST([support_class_code] AS [varchar](30)) AS [support_class_code],
      CAST([item_type_code] AS [varchar](10)) AS [item_type_code],
      CAST([item_model_code] AS [varchar](40)) AS [item_model_code],
      CAST([returnable_flag] AS [varchar](1)) AS [returnable_flag],
      CAST([advanced_exchange_enabled_flag] AS [varchar](1)) AS [advanced_exchange_enabled_flag],
      CAST([os_type_code] AS [varchar](10)) AS [os_type_code],
      CAST([min_storage] AS [decimal](38, 0)) AS [min_storage],
      CAST([min_storage_unit_code] AS [varchar](2)) AS [min_storage_unit_code],
      CAST([max_storage] AS [decimal](38, 0)) AS [max_storage],
      CAST([max_storage_unit_code] AS [varchar](2)) AS [max_storage_unit_code],
      CAST([storage_raid_code] AS [varchar](32)) AS [storage_raid_code],
      CAST([erp_staging_bom_code] AS [varchar](20)) AS [erp_staging_bom_code],
      CAST([erp_business_unit_code] AS [varchar](20)) AS [erp_business_unit_code],
      CAST([topline_reference_key] AS [varchar](40)) AS [topline_reference_key],
      CAST([esdl_flag] AS [varchar](1)) AS [esdl_flag],
      CAST([marketed_product_line_code] AS [varchar](30)) AS [marketed_product_line_code],
      CAST([license_category_code] AS [varchar](30)) AS [license_category_code],
      CAST([license_feature_code] AS [varchar](30)) AS [license_feature_code],
      CAST([subscription_enabled_flag] AS [varchar](1)) AS [subscription_enabled_flag],
      CAST([product_detail_key] AS [decimal](38, 0)) AS [product_detail_key],
      CAST([annuity_flag] AS [varchar](1)) AS [annuity_flag],
      CAST([available_kit_version] AS [varchar](4)) AS [available_kit_version],
      CAST([bid_level_pricing_date] AS [varchar](35)) AS [bid_level_pricing_date],
      CAST([bid_level_pricing_flag] AS [varchar](1)) AS [bid_level_pricing_flag],
      CAST([eccn_code] AS [varchar](8)) AS [eccn_code],
      CAST([encryption_type_code] AS [varchar](2)) AS [encryption_type_code],
      CAST([fcc_certification_code] AS [varchar](2)) AS [fcc_certification_code],
      CAST([fcc_id_number] AS [varchar](17)) AS [fcc_id_number],
      CAST([fda_certification_code] AS [varchar](1)) AS [fda_certification_code],
      CAST([gratis_demo_flag] AS [varchar](1)) AS [gratis_demo_flag],
      CAST([gratis_internal_copy_flag] AS [varchar](1)) AS [gratis_internal_copy_flag],
      CAST([gratis_update_flag] AS [varchar](1)) AS [gratis_update_flag],
      CAST([hardware_language_code] AS [varchar](2)) AS [hardware_language_code],
      CAST([hardware_power_code] AS [varchar](2)) AS [hardware_power_code],
      CAST([harmonized_code] AS [varchar](15)) AS [harmonized_code],
      CAST([installable_type_code] AS [varchar](1)) AS [installable_type_code],
      CAST([installable_type_date] AS [varchar](35)) AS [installable_type_date],
      CAST([internal_use_flag] AS [varchar](1)) AS [internal_use_flag],
      CAST([maint_price_exception_code] AS [varchar](12)) AS [maint_price_exception_code],
      CAST([maint_price_exception_date] AS [varchar](35)) AS [maint_price_exception_date],
      CAST([ncr_oem_ownership_code] AS [varchar](2)) AS [ncr_oem_ownership_code],
      CAST([ncrp_long_discontinued_flag] AS [varchar](1)) AS [ncrp_long_discontinued_flag],
      CAST([processor_quantity] AS [decimal](38, 0)) AS [processor_quantity],
      CAST([processor_type_key] AS [decimal](38, 0)) AS [processor_type_key],
      CAST([product_create_date] AS [varchar](35)) AS [product_create_date],
      CAST([publication_language_code] AS [varchar](2)) AS [publication_language_code],
      CAST([serialized_product_flag] AS [varchar](1)) AS [serialized_product_flag],
      CAST([shipping_height] AS [decimal](38, 5)) AS [shipping_height],
      CAST([shipping_length] AS [decimal](38, 5)) AS [shipping_length],
      CAST([shipping_weight] AS [decimal](38, 5)) AS [shipping_weight],
      CAST([shipping_width] AS [decimal](38, 5)) AS [shipping_width],
      CAST([software_language_code] AS [varchar](1)) AS [software_language_code],
      CAST([software_license_code] AS [varchar](1)) AS [software_license_code],
      CAST([sub_eccn_code] AS [varchar](9)) AS [sub_eccn_code],
      CAST([hazard_flag] AS [varchar](1)) AS [hazard_flag],
      CAST([software_license_type_code] AS [varchar](2)) AS [software_license_type_code],
      CAST([installation_hours] AS [decimal](38, 0)) AS [installation_hours],
      CAST([service_product_detail_key] AS [decimal](38, 0)) AS [service_product_detail_key],
      CAST([service_sponsor_org_key] AS [decimal](38, 0)) AS [service_sponsor_org_key],
      CAST([customs_description] AS [varchar](120)) AS [customs_description],
      CAST([service_invoice_flag] AS [varchar](1)) AS [service_invoice_flag],
      CAST([primary_uom_quantity] AS [decimal](38, 0)) AS [primary_uom_quantity],
      CAST([wot_extract_flag] AS [varchar](1)) AS [wot_extract_flag],
      CAST([primary_uom_code] AS [varchar](3)) AS [primary_uom_code],
      CAST([costing_uom_code] AS [varchar](1)) AS [costing_uom_code],
      CAST([smd_product_code] AS [varchar](4)) AS [smd_product_code],
      CAST([sell_unit_upc] AS [varchar](12)) AS [sell_unit_upc],
      CAST([master_carton_upc] AS [varchar](14)) AS [master_carton_upc],
      CAST([master_carton_quantity] AS [decimal](38, 0)) AS [master_carton_quantity],
      CAST([inner_carton_upc] AS [varchar](14)) AS [inner_carton_upc],
      CAST([inner_carton_quantity] AS [decimal](38, 0)) AS [inner_carton_quantity],
      CAST([retail_catalog_flag] AS [varchar](1)) AS [retail_catalog_flag],
      CAST([financial_catalog_flag] AS [varchar](1)) AS [financial_catalog_flag],
      CAST([ncr_direct_flag] AS [varchar](1)) AS [ncr_direct_flag],
      CAST([order_entry_message] AS [varchar](650)) AS [order_entry_message],
      CAST([product_comments] AS [varchar](650)) AS [product_comments],
    FROM [trans_product_gsdb_gsdb].[product_detail], 
),
rn as (
    SELECT  *, ROW_NUMBER() OVER (PARTITION BY hash_key ORDER BY 
				  infa_operation_time DESC,
                infa_sortable_sequence  DESC
        ) as _ELT_ROWNUMBERED
    FROM    gen_hashkey
),
data as (
    SELECT  *
    FROM    rn
    WHERE _ELT_ROWNUMBERED = 1
)
MERGE INTO    [trans_product_gsdb_gsdb].[product_detail] tgt
USING (
    SELECT  *
    FROM    data
) src
ON ( src.[hash_key] = tgt.[hash_key] )
WHEN MATCHED THEN 
UPDATE SET
    [tgt].[imprintable_flag] = [src].[imprintable_flag],
    [tgt].[imprint_format_id] = [src].[imprint_format_id],
    [tgt].[product_weight] = [src].[product_weight],
    [tgt].[ipp_product_flag] = [src].[ipp_product_flag],
    [tgt].[ipp_restricted_flag] = [src].[ipp_restricted_flag],
    [tgt].[ipp_subscription_flag] = [src].[ipp_subscription_flag],
    [tgt].[prepaid_maint_flag] = [src].[prepaid_maint_flag],
    [tgt].[prepaid_months] = [src].[prepaid_months],
    [tgt].[prepaid_category_code] = [src].[prepaid_category_code],
    [tgt].[royalty_flag] = [src].[royalty_flag],
    [tgt].[billing_type_code] = [src].[billing_type_code],
    [tgt].[item_group_code] = [src].[item_group_code],
    [tgt].[sub_item_group_code] = [src].[sub_item_group_code],
    [tgt].[manufacturer_part_number] = [src].[manufacturer_part_number],
    [tgt].[ccats_number] = [src].[ccats_number],
    [tgt].[es_business_unit_code] = [src].[es_business_unit_code],
    [tgt].[advocated_solution_code] = [src].[advocated_solution_code],
    [tgt].[service_tier_code] = [src].[service_tier_code],
    [tgt].[tm_remote_support] = [src].[tm_remote_support],
    [tgt].[cross_selling_type_code] = [src].[cross_selling_type_code],
    [tgt].[hw_sol_set_classification_code] = [src].[hw_sol_set_classification_code],
    [tgt].[support_class_code] = [src].[support_class_code],
    [tgt].[item_type_code] = [src].[item_type_code],
    [tgt].[item_model_code] = [src].[item_model_code],
    [tgt].[returnable_flag] = [src].[returnable_flag],
    [tgt].[advanced_exchange_enabled_flag] = [src].[advanced_exchange_enabled_flag],
    [tgt].[os_type_code] = [src].[os_type_code],
    [tgt].[min_storage] = [src].[min_storage],
    [tgt].[min_storage_unit_code] = [src].[min_storage_unit_code],
    [tgt].[max_storage] = [src].[max_storage],
    [tgt].[max_storage_unit_code] = [src].[max_storage_unit_code],
    [tgt].[storage_raid_code] = [src].[storage_raid_code],
    [tgt].[erp_staging_bom_code] = [src].[erp_staging_bom_code],
    [tgt].[erp_business_unit_code] = [src].[erp_business_unit_code],
    [tgt].[topline_reference_key] = [src].[topline_reference_key],
    [tgt].[esdl_flag] = [src].[esdl_flag],
    [tgt].[marketed_product_line_code] = [src].[marketed_product_line_code],
    [tgt].[license_category_code] = [src].[license_category_code],
    [tgt].[license_feature_code] = [src].[license_feature_code],
    [tgt].[subscription_enabled_flag] = [src].[subscription_enabled_flag],
    [tgt].[product_detail_key] = [src].[product_detail_key],
    [tgt].[annuity_flag] = [src].[annuity_flag],
    [tgt].[available_kit_version] = [src].[available_kit_version],
    [tgt].[bid_level_pricing_date] = [src].[bid_level_pricing_date],
    [tgt].[bid_level_pricing_flag] = [src].[bid_level_pricing_flag],
    [tgt].[eccn_code] = [src].[eccn_code],
    [tgt].[encryption_type_code] = [src].[encryption_type_code],
    [tgt].[fcc_certification_code] = [src].[fcc_certification_code],
    [tgt].[fcc_id_number] = [src].[fcc_id_number],
    [tgt].[fda_certification_code] = [src].[fda_certification_code],
    [tgt].[gratis_demo_flag] = [src].[gratis_demo_flag],
    [tgt].[gratis_internal_copy_flag] = [src].[gratis_internal_copy_flag],
    [tgt].[gratis_update_flag] = [src].[gratis_update_flag],
    [tgt].[hardware_language_code] = [src].[hardware_language_code],
    [tgt].[hardware_power_code] = [src].[hardware_power_code],
    [tgt].[harmonized_code] = [src].[harmonized_code],
    [tgt].[installable_type_code] = [src].[installable_type_code],
    [tgt].[installable_type_date] = [src].[installable_type_date],
    [tgt].[internal_use_flag] = [src].[internal_use_flag],
    [tgt].[maint_price_exception_code] = [src].[maint_price_exception_code],
    [tgt].[maint_price_exception_date] = [src].[maint_price_exception_date],
    [tgt].[ncr_oem_ownership_code] = [src].[ncr_oem_ownership_code],
    [tgt].[ncrp_long_discontinued_flag] = [src].[ncrp_long_discontinued_flag],
    [tgt].[processor_quantity] = [src].[processor_quantity],
    [tgt].[processor_type_key] = [src].[processor_type_key],
    [tgt].[product_create_date] = [src].[product_create_date],
    [tgt].[publication_language_code] = [src].[publication_language_code],
    [tgt].[serialized_product_flag] = [src].[serialized_product_flag],
    [tgt].[shipping_height] = [src].[shipping_height],
    [tgt].[shipping_length] = [src].[shipping_length],
    [tgt].[shipping_weight] = [src].[shipping_weight],
    [tgt].[shipping_width] = [src].[shipping_width],
    [tgt].[software_language_code] = [src].[software_language_code],
    [tgt].[software_license_code] = [src].[software_license_code],
    [tgt].[sub_eccn_code] = [src].[sub_eccn_code],
    [tgt].[hazard_flag] = [src].[hazard_flag],
    [tgt].[software_license_type_code] = [src].[software_license_type_code],
    [tgt].[installation_hours] = [src].[installation_hours],
    [tgt].[service_product_detail_key] = [src].[service_product_detail_key],
    [tgt].[service_sponsor_org_key] = [src].[service_sponsor_org_key],
    [tgt].[customs_description] = [src].[customs_description],
    [tgt].[service_invoice_flag] = [src].[service_invoice_flag],
    [tgt].[primary_uom_quantity] = [src].[primary_uom_quantity],
    [tgt].[wot_extract_flag] = [src].[wot_extract_flag],
    [tgt].[primary_uom_code] = [src].[primary_uom_code],
    [tgt].[costing_uom_code] = [src].[costing_uom_code],
    [tgt].[smd_product_code] = [src].[smd_product_code],
    [tgt].[sell_unit_upc] = [src].[sell_unit_upc],
    [tgt].[master_carton_upc] = [src].[master_carton_upc],
    [tgt].[master_carton_quantity] = [src].[master_carton_quantity],
    [tgt].[inner_carton_upc] = [src].[inner_carton_upc],
    [tgt].[inner_carton_quantity] = [src].[inner_carton_quantity],
    [tgt].[retail_catalog_flag] = [src].[retail_catalog_flag],
    [tgt].[financial_catalog_flag] = [src].[financial_catalog_flag],
    [tgt].[ncr_direct_flag] = [src].[ncr_direct_flag],
    [tgt].[order_entry_message] = [src].[order_entry_message],
    [tgt].[product_comments] = [src].[product_comments],
    [tgt].[ingest_partition] = [src].[ingest_partition],
    [tgt].[ingest_channel] = [src].[ingest_channel],
    [tgt].[file_path] = [src].[file_path],
    [tgt].[root_path] = [src].[root_path],
    [tgt].[trans_load_date_time_utc] = GETDATE(),
    [tgt].[adle_transaction_code] = [src].[infa_operation_type],
    [tgt].[infa_operation_time]=[src].[infa_operation_time],
	[tgt].[infa_sortable_sequence]=[src].[infa_sortable_sequence],
    [tgt].[pipeline_name] = @pipeline_name,
    [tgt].[pipeline_run_id] = @pipeline_run_id,
    [tgt].[pipeline_trigger_name] = @pipeline_trigger_name,
    [tgt].[pipeline_trigger_id] = @pipeline_trigger_id,
    [tgt].[pipeline_trigger_type] = @pipeline_trigger_type,
    [tgt].[pipeline_trigger_date_time_utc] = @pipeline_trigger_date_time_utc
WHEN NOT MATCHED THEN 
    INSERT (
    [imprintable_flag],
    [imprint_format_id],
    [product_weight],
    [ipp_product_flag],
    [ipp_restricted_flag],
    [ipp_subscription_flag],
    [prepaid_maint_flag],
    [prepaid_months],
    [prepaid_category_code],
    [royalty_flag],
    [billing_type_code],
    [item_group_code],
    [sub_item_group_code],
    [manufacturer_part_number],
    [ccats_number],
    [es_business_unit_code],
    [advocated_solution_code],
    [service_tier_code],
    [tm_remote_support],
    [cross_selling_type_code],
    [hw_sol_set_classification_code],
    [support_class_code],
    [item_type_code],
    [item_model_code],
    [returnable_flag],
    [advanced_exchange_enabled_flag],
    [os_type_code],
    [min_storage],
    [min_storage_unit_code],
    [max_storage],
    [max_storage_unit_code],
    [storage_raid_code],
    [erp_staging_bom_code],
    [erp_business_unit_code],
    [topline_reference_key],
    [esdl_flag],
    [marketed_product_line_code],
    [license_category_code],
    [license_feature_code],
    [subscription_enabled_flag],
    [product_detail_key],
    [annuity_flag],
    [available_kit_version],
    [bid_level_pricing_date],
    [bid_level_pricing_flag],
    [eccn_code],
    [encryption_type_code],
    [fcc_certification_code],
    [fcc_id_number],
    [fda_certification_code],
    [gratis_demo_flag],
    [gratis_internal_copy_flag],
    [gratis_update_flag],
    [hardware_language_code],
    [hardware_power_code],
    [harmonized_code],
    [installable_type_code],
    [installable_type_date],
    [internal_use_flag],
    [maint_price_exception_code],
    [maint_price_exception_date],
    [ncr_oem_ownership_code],
    [ncrp_long_discontinued_flag],
    [processor_quantity],
    [processor_type_key],
    [product_create_date],
    [publication_language_code],
    [serialized_product_flag],
    [shipping_height],
    [shipping_length],
    [shipping_weight],
    [shipping_width],
    [software_language_code],
    [software_license_code],
    [sub_eccn_code],
    [hazard_flag],
    [software_license_type_code],
    [installation_hours],
    [service_product_detail_key],
    [service_sponsor_org_key],
    [customs_description],
    [service_invoice_flag],
    [primary_uom_quantity],
    [wot_extract_flag],
    [primary_uom_code],
    [costing_uom_code],
    [smd_product_code],
    [sell_unit_upc],
    [master_carton_upc],
    [master_carton_quantity],
    [inner_carton_upc],
    [inner_carton_quantity],
    [retail_catalog_flag],
    [financial_catalog_flag],
    [ncr_direct_flag],
    [order_entry_message],
    [product_comments],
    [ingest_partition], 
    [ingest_channel], 
    [file_path], 
    [root_path], 
    [pipeline_name], 
    [pipeline_run_id], 
    [pipeline_trigger_name], 
    [pipeline_trigger_id], 
    [pipeline_trigger_type], 
    [pipeline_trigger_date_time_utc], 
    [trans_load_date_time_utc], 
    [adle_transaction_code], 
    [infa_operation_time], 
    [infa_sortable_sequence], 
    [hash_key] 
)VALUES(
    [src].[imprintable_flag],
    [src].[imprint_format_id],
    [src].[product_weight],
    [src].[ipp_product_flag],
    [src].[ipp_restricted_flag],
    [src].[ipp_subscription_flag],
    [src].[prepaid_maint_flag],
    [src].[prepaid_months],
    [src].[prepaid_category_code],
    [src].[royalty_flag],
    [src].[billing_type_code],
    [src].[item_group_code],
    [src].[sub_item_group_code],
    [src].[manufacturer_part_number],
    [src].[ccats_number],
    [src].[es_business_unit_code],
    [src].[advocated_solution_code],
    [src].[service_tier_code],
    [src].[tm_remote_support],
    [src].[cross_selling_type_code],
    [src].[hw_sol_set_classification_code],
    [src].[support_class_code],
    [src].[item_type_code],
    [src].[item_model_code],
    [src].[returnable_flag],
    [src].[advanced_exchange_enabled_flag],
    [src].[os_type_code],
    [src].[min_storage],
    [src].[min_storage_unit_code],
    [src].[max_storage],
    [src].[max_storage_unit_code],
    [src].[storage_raid_code],
    [src].[erp_staging_bom_code],
    [src].[erp_business_unit_code],
    [src].[topline_reference_key],
    [src].[esdl_flag],
    [src].[marketed_product_line_code],
    [src].[license_category_code],
    [src].[license_feature_code],
    [src].[subscription_enabled_flag],
    [src].[product_detail_key],
    [src].[annuity_flag],
    [src].[available_kit_version],
    [src].[bid_level_pricing_date],
    [src].[bid_level_pricing_flag],
    [src].[eccn_code],
    [src].[encryption_type_code],
    [src].[fcc_certification_code],
    [src].[fcc_id_number],
    [src].[fda_certification_code],
    [src].[gratis_demo_flag],
    [src].[gratis_internal_copy_flag],
    [src].[gratis_update_flag],
    [src].[hardware_language_code],
    [src].[hardware_power_code],
    [src].[harmonized_code],
    [src].[installable_type_code],
    [src].[installable_type_date],
    [src].[internal_use_flag],
    [src].[maint_price_exception_code],
    [src].[maint_price_exception_date],
    [src].[ncr_oem_ownership_code],
    [src].[ncrp_long_discontinued_flag],
    [src].[processor_quantity],
    [src].[processor_type_key],
    [src].[product_create_date],
    [src].[publication_language_code],
    [src].[serialized_product_flag],
    [src].[shipping_height],
    [src].[shipping_length],
    [src].[shipping_weight],
    [src].[shipping_width],
    [src].[software_language_code],
    [src].[software_license_code],
    [src].[sub_eccn_code],
    [src].[hazard_flag],
    [src].[software_license_type_code],
    [src].[installation_hours],
    [src].[service_product_detail_key],
    [src].[service_sponsor_org_key],
    [src].[customs_description],
    [src].[service_invoice_flag],
    [src].[primary_uom_quantity],
    [src].[wot_extract_flag],
    [src].[primary_uom_code],
    [src].[costing_uom_code],
    [src].[smd_product_code],
    [src].[sell_unit_upc],
    [src].[master_carton_upc],
    [src].[master_carton_quantity],
    [src].[inner_carton_upc],
    [src].[inner_carton_quantity],
    [src].[retail_catalog_flag],
    [src].[financial_catalog_flag],
    [src].[ncr_direct_flag],
    [src].[order_entry_message],
    [src].[product_comments],
    [src].[ingest_partition], 
    [src].[ingest_channel], 
    [src].[file_path], 
    [src].[root_path], 
    @pipeline_name, 
    @pipeline_run_id, 
    @pipeline_trigger_name, 
    @pipeline_trigger_id, 
    @pipeline_trigger_type, 
    @pipeline_trigger_date_time_utc, 
    GETDATE(), 
    [src].[infa_operation_type], 
    [src].[infa_operation_time], 
    [src].[infa_sortable_sequence], 
    [src].[hash_key]
    );
END TRY
BEGIN CATCH
    DECLARE @db_name VARCHAR(200),
        @schema_name VARCHAR(200),
        @error_nbr INT,
        @error_severity INT,
        @error_state INT,
        @stored_proc_name VARCHAR(200),
        @error_message VARCHAR(8000),
        @created_date_time DATETIME2

    SET @db_name=DB_NAME()
    SET @schema_name=SUBSTRING (@pipeline_name, CHARINDEX('2', @pipeline_name) + 1, LEN(@pipeline_name) - CHARINDEX('2', @pipeline_name) - 3 )
    SET @error_nbr=ERROR_NUMBER()
    SET @error_severity=ERROR_SEVERITY()
    SET @error_state=ERROR_STATE()
    SET @stored_proc_name=ERROR_PROCEDURE()
    SET @error_message=ERROR_MESSAGE()
    SET @created_date_time=GETDATE()

    EXECUTE [adle_platform_orchestration].[elt_error_log_proc]
        @db_name,
        'ERROR',
        @schema_name,
        @error_nbr,
        @error_severity,
        @error_state,
        @stored_proc_name,
        'PROC',
        @error_message,
        @created_date_time,
        @pipeline_name,
        @pipeline_run_id,
        @pipeline_trigger_name,
        @pipeline_trigger_id,
        @pipeline_trigger_type,
        @pipeline_trigger_date_time_utc
        ;
    THROW;
END CATCH
;
GO
