CREATE TABLE product.product_detail_temp (
  [infa_operation_time] [varchar](35) NULL,
  [infa_operation_type] [varchar](1) NULL,
  [advanced_exchange_enabled_flag] [varchar](1),
  [advocated_solution_code] [varchar](3),
  [annuity_flag] [varchar](1),
  [available_kit_version] [varchar](4),
  [bid_level_pricing_date] [varchar](35),
  [bid_level_pricing_flag] [varchar](1),
  [billing_type_code] [varchar](5),
  [ccats_number] [varchar](7),
  [costing_uom_code] [varchar](1),
  [cross_selling_type_code] [varchar](10),
  [customs_description] [varchar](120),
  [eccn_code] [varchar](8),
  [encryption_type_code] [varchar](2),
  [erp_business_unit_code] [varchar](20),
  [erp_staging_bom_code] [varchar](20),
  [es_business_unit_code] [varchar](5),
  [esdl_flag] [varchar](1),
  [fcc_certification_code] [varchar](2),
  [fcc_id_number] [varchar](17),
  [fda_certification_code] [varchar](1),
  [financial_catalog_flag] [varchar](1),
  [gratis_demo_flag] [varchar](1),
  [gratis_internal_copy_flag] [varchar](1),
  [gratis_update_flag] [varchar](1),
  [hardware_language_code] [varchar](2),
  [hardware_power_code] [varchar](2),
  [harmonized_code] [varchar](15),
  [hazard_flag] [varchar](1),
  [hw_sol_set_classification_code] [varchar](10),
  [imprint_format_id] [varchar](3),
  [imprintable_flag] [varchar](1),
  [inner_carton_quantity] [decimal](38, 0),
  [inner_carton_upc] [varchar](14),
  [installable_type_code] [varchar](1),
  [installable_type_date] [varchar](35),
  [installation_hours] [decimal](38, 0),
  [internal_use_flag] [varchar](1),
  [ipp_product_flag] [varchar](1),
  [ipp_restricted_flag] [varchar](1),
  [ipp_subscription_flag] [varchar](1),
  [item_group_code] [varchar](5),
  [item_model_code] [varchar](40),
  [item_type_code] [varchar](10),
  [license_category_code] [varchar](30),
  [license_feature_code] [varchar](30),
  [maint_price_exception_code] [varchar](12),
  [maint_price_exception_date] [varchar](35),
  [manufacturer_part_number] [varchar](50),
  [marketed_product_line_code] [varchar](30),
  [master_carton_quantity] [decimal](38, 0),
  [master_carton_upc] [varchar](14),
  [max_storage] [decimal](38, 0),
  [max_storage_unit_code] [varchar](2),
  [min_storage] [decimal](38, 0),
  [min_storage_unit_code] [varchar](2),
  [ncr_direct_flag] [varchar](1),
  [ncr_oem_ownership_code] [varchar](2),
  [ncrp_long_discontinued_flag] [varchar](1),
  [order_entry_message] [varchar](650),
  [os_type_code] [varchar](10),
  [prepaid_category_code] [varchar](1),
  [prepaid_maint_flag] [varchar](1),
  [prepaid_months] [decimal](38, 0),
  [primary_uom_code] [varchar](3),
  [primary_uom_quantity] [decimal](38, 0),
  [processor_quantity] [decimal](38, 0),
  [processor_type_key] [decimal](38, 0),
  [product_comments] [varchar](650),
  [product_create_date] [varchar](35),
  [product_detail_key] [decimal](38, 0),
  [product_weight] [decimal](38, 0),
  [publication_language_code] [varchar](2),
  [retail_catalog_flag] [varchar](1),
  [returnable_flag] [varchar](1),
  [royalty_flag] [varchar](1),
  [sell_unit_upc] [varchar](12),
  [serialized_product_flag] [varchar](1),
  [service_invoice_flag] [varchar](1),
  [service_product_detail_key] [decimal](38, 0),
  [service_sponsor_org_key] [decimal](38, 0),
  [service_tier_code] [varchar](2),
  [shipping_height] [decimal](38, 0),
  [shipping_length] [decimal](38, 0),
  [shipping_weight] [decimal](38, 0),
  [shipping_width] [decimal](38, 0),
  [smd_product_code] [varchar](4),
  [software_language_code] [varchar](1),
  [software_license_code] [varchar](1),
  [software_license_type_code] [varchar](2),
  [storage_raid_code] [varchar](32),
  [sub_eccn_code] [varchar](9),
  [sub_item_group_code] [varchar](5),
  [subscription_enabled_flag] [varchar](1),
  [support_class_code] [varchar](30),
  [tm_remote_support] [varchar](1),
  [topline_reference_key] [varchar](40),
  [wot_extract_flag] [varchar](1),
  [ingest_partition] [varchar](100) NULL,
  [ingest_channel] [varchar](100) NULL,
  [file_path] [varchar](100) NULL,
  [root_path] [varchar](100) NULL
)
WITH
(
  DISTRIBUTION = ROUND_ROBIN,
  HEAP
)
GO
